### GET request to example server
POST http://localhost:8080/consultants
Content-Type: application/json

{
  "email" : "consultant1@service.com",
  "nickname" : "consultant",
  "name" : "상담원",
  "password" : "password",
  "confirmedPassword": "password",
  "gender": "MALE",
  "phoneNumber": "821012345678",
  "birthday": "2000-01-01",
  "role": "ROLE_CONSULTANT"
}
###